export const TEAMMEMBERS = [
  {
    id: 0,
    name: "Alex Marston",
    title: "Develoer",
    image: "./pictures/Team/alexm.jpg",
    bio: "",
  },
  {
    id: 1,
    name: "David Ditto",
    title: "Developer",
    image: "./pictures/male.png",
    bio: "",
  },
  {
    id: 2,
    name: "Demarcus Williams",
    title: "Developer",
    image: "./pictures/male.png",
    bio: "",
  },
  {
    id: 3,
    name: "Barry Collins",
    title: "Developer",
    image: "./pictures/male.png",
    bio: "",
  },
  {
    id: 4,
    name: "Luke McFalls",
    title: "Developer",
    image: "./pictures/male.png",
    bio: "",
  },
  {
    id: 5,
    name: "Marcellas Colbert",
    title: "Developer",
    image: "./pictures/Team/marcellusC.jpg",
    bio: "",
  },
  {
    id: 6,
    name: "Jason Lyles",
    title: "Developer",
    image: "./pictures/male.png",
    bio: "",
  },
  {
    id: 7,
    name: "Kenneth Gourly",
    title: "Developer",
    image: "./pictures/male.png",
    bio: "",
  },
  {
    id: 8,
    name: "Roy Yates",
    title: "Developer",
    image: "./pictures/male.png",
    bio: "",
  },
  {
    id: 9,
    name: "Sean Hosman",
    title: "President",
    image: "./pictures/male.png",
    bio: "",
  },
  {
    id: 10,
    name: "Stacey Books",
    title: "Program Manager",
    image: "./pictures/male.png",
    bio: "",
  },
  {
    id: 11,
    name: "Zach Hosman",
    title: "Program Manager",
    image: "./pictures/male.png",
    bio: "",
  },
  {
    id: 12,
    name: "Matt Payn",
    title: "Customer Relations",
    image: "./pictures/male.png",
    bio: "",
  },
  {
    id: 13,
    name: "Anup Cherian",
    title: "Project Manager",
    image: "./pictures/male.png",
    bio: "",
  },
  {
    id: 14,
    name: "Robert Puzey",
    title: "Product Manager",
    image: "./pictures/male.png",
    bio: "",
  },
];
