export const TEAMMEMBERS = [
  {
    id: 0,
    name: "Alex Marston",
    title: "Developer",
    image: "./pictures/Team/alexm.jpg",
    bio: "",
  },
  {
    id: 1,
    name: "David Ditto",
    title: "Developer",
    image: "./pictures/male.png",
    bio: "Coming Soon to the Team!",
  },
  {
    id: 2,
    name: "Demarcus Williams",
    title: "Developer",
    image: "./pictures/male.png",
    bio: "Coming Soon to the Team!",
  },
  {
    id: 3,
    name: "Barry Collins",
    title: "Developer",
    image: "./pictures/male.png",
    bio: "Coming Soon to the Team!",
  },
  {
    id: 4,
    name: "Luke McFalls",
    title: "Developer",
    image: "./pictures/male.png",
    bio: "Coming Soon to the Team!",
  },
  {
    id: 5,
    name: "Marcellas Colbert",
    title: "Developer",
    image: "./pictures/Team/marcellusC.jpg",
    bio: "",
  },
  {
    id: 6,
    name: "Jason Lyles",
    title: "Developer",
    image: "./pictures/male.png",
    bio: "Coming Soon to the Team!",
  },
  {
    id: 7,
    name: "Kenneth Gourly",
    title: "Developer",
    image: "./pictures/male.png",
    bio: "",
  },
  {
    id: 8,
    name: "Roy Yates",
    title: "Developer",
    image: "./pictures/male.png",
    bio: "",
  },
  {
    id: 9,
    name: "Sean Hosman",
    title: "President",
    image: "./pictures/Team/seanH.jpg",
    bio: "",
  },
  {
    id: 10,
    name: "Stacey Books",
    title: "Program Manager",
    image: "./pictures/Team/staceyB.jpg",
    bio: "Stacey Books-Mesko is the Program Manager and the heart of Persevere. As Program Manager, she is responsible for the day-to-day implementation and management of Persevere’s coding and employment programs within institutions and community agencies. Ms. Books-Mesko is well acquainted with the skills, perseverance, and support ex-offenders need to succeed in the job market and community. Not only does she have 17 years of experience in the human resources and management fields, but she is an ex-offender herself, and she is committed to helping others move beyond their pasts to create successful futures for themselves. Under her leadership, Persevere has the best blend of technical expertise, inspiration, and ongoing support that participants will need to change their lives.",
  },
  {
    id: 11,
    name: "Zach Hosman",
    title: "Program Manager",
    image: "./pictures/male.png",
    bio: "",
  },
  {
    id: 12,
    name: "Matt Payn",
    title: "Customer Relations",
    image: "./pictures/male.png",
    bio: "",
  },
  {
    id: 13,
    name: "Anup Cherian",
    title: "Project Manager",
    image: "./pictures/male.png",
    bio: "",
  },
  {
    id: 14,
    name: "Robert Puzey",
    title: "Product Manager",
    image: "./pictures/Team/robertP.png",
    bio: "My goal is to help create products that people love. With 20+ years of experience managing products I have:\n\t•Created CaptionCall which is now a $300+ million division of Sorenson Communications\n\t•Managed dozens of hardware, software, and service products through their lifecycles\n\t•Leveraged Agile, Scrum, Kanban methodologies as a Product Owner\n\t•Designed meaningful customer experiences\n•As a servant leader, helped others develop & perform",
  },
];
